package com.pecunia.category.application.port.in;

import com.pecunia.category.domain.CategoryType;
import com.pecunia.category.domain.HexColor;
import com.pecunia.sharedkernel.CategoryId;
import com.pecunia.sharedkernel.UserId;
import java.util.Optional;

/**
 * Input for {@link CreateCategory}.
 *
 * <p>Speaks the domain's language (value objects), not primitives: the web layer
 * translates the request DTO into these types. The {@code id} is generated by
 * the service, not supplied here. {@code icon} and {@code parent} are
 * {@link Optional} to keep the module boundary null-free.
 */
public record CreateCategoryCommand(
        UserId owner,
        String name,
        CategoryType type,
        HexColor color,
        Optional<String> icon,
        Optional<CategoryId> parent,
        int displayOrder) {}
