package com.pecunia.account.web.mapper;

import com.pecunia.account.application.port.in.OpenAccountCommand;
import com.pecunia.account.application.readmodel.AccountView;
import com.pecunia.account.domain.Iban;
import com.pecunia.account.web.dto.AccountResponse;
import com.pecunia.account.web.dto.OpenAccountRequest;
import com.pecunia.sharedkernel.Money;
import com.pecunia.sharedkernel.UserId;
import java.math.BigDecimal;
import java.util.Currency;
import java.util.Optional;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.ReportingPolicy;

/**
 * Maps between the generated web DTOs and the account application types.
 *
 * <p>The inbound direction {@code toCommand} is generated by MapStruct: its
 * source is the generated DTO (JavaBean getters) and its target a record, both
 * of which MapStruct reads and writes natively. The outbound direction
 * {@code toDto} now maps from the {@link AccountView} read model — a record,
 * so the fluent-accessor obstacle that once forced a hand-written mapping from
 * the aggregate (and the custom {@code AccessorNamingStrategy} SPI it would
 * have required) is gone. It stays a small default method by choice: the
 * {@code Optional<Iban>} unwrap and the Money formatting would each need a
 * qualified helper anyway, at which point the explicit builder chain is
 * shorter than its annotation-driven equivalent.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface AccountMapper {

    // --- Inbound: request (+ owner resolved from the session) -> command --------

    @Mapping(target = "owner", source = "owner")
    @Mapping(target = "type", source = "request.type")
    @Mapping(target = "name", source = "request.name")
    @Mapping(target = "iban", source = "request.iban", qualifiedByName = "toIban")
    @Mapping(target = "initialBalance", source = "request.initialBalance", qualifiedByName = "toDomainMoney")
    OpenAccountCommand toCommand(OpenAccountRequest request, UserId owner);

    /**
     * Builds the {@link Iban} value object — the point where an
     * {@code InvalidIbanException} surfaces (mapped to 400 by the advice). A
     * {@code null} value (a credit card, or an absent field) maps to
     * {@link Optional#empty()} to keep the command null-free; the domain then
     * enforces the IBAN-required / IBAN-forbidden rule per account type.
     */
    @Named("toIban")
    default Optional<Iban> toIban(String iban) {
        return iban == null ? Optional.empty() : Optional.of(new Iban(iban));
    }

    @Named("toDomainMoney")
    default Money toDomainMoney(com.pecunia.account.web.dto.Money money) {
        return Money.of(new BigDecimal(money.getAmount()), Currency.getInstance(money.getCurrency()));
    }

    // --- Outbound: read model -> response DTO (hand-written, see above) ---------

    default AccountResponse toDto(AccountView account) {
        return new AccountResponse()
                .id(account.id().value())
                .type(toDtoType(account.type()))
                .name(account.name())
                .iban(account.iban().map(Iban::value).orElse(null))
                .status(toDtoStatus(account.status()))
                .initialBalance(toDtoMoney(account.initialBalance()));
    }

    // Enum name-based conversions: generated by MapStruct (compile-time checked
    // that every domain constant has a matching DTO constant).
    com.pecunia.account.web.dto.AccountType toDtoType(com.pecunia.account.domain.AccountType type);

    com.pecunia.account.web.dto.AccountStatus toDtoStatus(com.pecunia.account.domain.AccountStatus status);

    default com.pecunia.account.web.dto.Money toDtoMoney(Money money) {
        return new com.pecunia.account.web.dto.Money(
                money.amount().toPlainString(), money.currency().getCurrencyCode());
    }
}
