package com.pecunia.account.web.mapper;

import com.pecunia.account.application.port.in.OpenAccountCommand;
import com.pecunia.account.domain.Account;
import com.pecunia.account.domain.Iban;
import com.pecunia.account.web.dto.AccountResponse;
import com.pecunia.account.web.dto.OpenAccountRequest;
import com.pecunia.shared.Money;
import com.pecunia.shared.UserId;
import java.math.BigDecimal;
import java.util.Currency;
import java.util.Optional;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.ReportingPolicy;

/**
 * Maps between the generated web DTOs and the account application/domain types.
 *
 * <p>Asymmetric by design. The inbound direction {@code toCommand} is generated
 * by MapStruct: its source is the generated DTO (JavaBean getters) and its
 * target a record, both of which MapStruct reads and writes natively. The
 * outbound direction {@code toDto} is hand-written, because its source is the
 * {@link Account} aggregate, whose deliberately fluent accessors
 * ({@code account.id()}, not {@code getId()} — ADR-0013) MapStruct's default
 * {@code AccessorNamingStrategy} does not recognise. Teaching MapStruct those
 * accessors requires a custom SPI shipped in a separate module; that is deferred
 * until a second bounded context adds a domain&rarr;DTO mapper (rule of three).
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface AccountMapper {

    // --- Inbound: request (+ owner resolved from the session) -> command --------

    @Mapping(target = "owner", source = "owner")
    @Mapping(target = "type", source = "request.type")
    @Mapping(target = "name", source = "request.name")
    @Mapping(target = "iban", source = "request.iban", qualifiedByName = "toIban")
    @Mapping(target = "initialBalance", source = "request.initialBalance", qualifiedByName = "toDomainMoney")
    OpenAccountCommand toCommand(OpenAccountRequest request, UserId owner);

    /**
     * Builds the {@link Iban} value object — the point where an
     * {@code InvalidIbanException} surfaces (mapped to 400 by the advice). A
     * {@code null} value (a credit card, or an absent field) maps to
     * {@link Optional#empty()} to keep the command null-free; the domain then
     * enforces the IBAN-required / IBAN-forbidden rule per account type.
     */
    @Named("toIban")
    default Optional<Iban> toIban(String iban) {
        return iban == null ? Optional.empty() : Optional.of(new Iban(iban));
    }

    @Named("toDomainMoney")
    default Money toDomainMoney(com.pecunia.account.web.dto.Money money) {
        return Money.of(new BigDecimal(money.getAmount()), Currency.getInstance(money.getCurrency()));
    }

    // --- Outbound: domain aggregate -> response DTO (hand-written, see above) ----

    default AccountResponse toDto(Account account) {
        return new AccountResponse()
                .id(account.id().value())
                .type(toDtoType(account.type()))
                .name(account.name())
                .iban(account.iban() == null ? null : account.iban().value())
                .status(toDtoStatus(account.status()))
                .initialBalance(toDtoMoney(account.initialBalance()));
    }

    // Enum name-based conversions: generated by MapStruct (compile-time checked
    // that every domain constant has a matching DTO constant).
    com.pecunia.account.web.dto.AccountType toDtoType(com.pecunia.account.domain.AccountType type);

    com.pecunia.account.web.dto.AccountStatus toDtoStatus(com.pecunia.account.domain.AccountStatus status);

    default com.pecunia.account.web.dto.Money toDtoMoney(Money money) {
        return new com.pecunia.account.web.dto.Money(
                money.amount().toPlainString(), money.currency().getCurrencyCode());
    }
}
