package com.pecunia.category.web.mapper;

import com.pecunia.category.application.port.in.CreateCategoryCommand;
import com.pecunia.category.application.readmodel.CategoryNode;
import com.pecunia.category.application.readmodel.CategoryView;
import com.pecunia.category.domain.HexColor;
import com.pecunia.category.web.dto.CategoryNodeResponse;
import com.pecunia.category.web.dto.CategoryResponse;
import com.pecunia.category.web.dto.CreateCategoryRequest;
import com.pecunia.sharedkernel.CategoryId;
import java.util.Optional;
import java.util.UUID;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.ReportingPolicy;

/**
 * Maps between the generated web DTOs and the category application types.
 *
 * <p>Follows {@code AccountMapper}: the inbound {@code toCreateCommand} is
 * MapStruct-driven (DTO getters to a record, with {@code @Named} helpers where
 * a value object or an {@link Optional} must be built), while the outbound
 * directions are hand-written {@code default} methods. Every outbound property
 * needs unwrapping — a {@link CategoryId} to a {@code UUID}, a {@link HexColor}
 * to a {@code String}, an {@code Optional} to a nullable field — so the explicit
 * builder chain is shorter and clearer than its annotation-driven equivalent.
 * The {@code name} on creation carries the raw input: the domain strips it.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface CategoryMapper {

    // --- Inbound: request (+ owner resolved from the session) -> command --------

    // name, type (enum by constant name) and displayOrder map by matching name.
    @Mapping(target = "color", source = "color", qualifiedByName = "toHexColor")
    @Mapping(target = "icon", source = "icon", qualifiedByName = "toOptionalString")
    @Mapping(target = "parent", source = "parentId", qualifiedByName = "toOptionalCategoryId")
    CreateCategoryCommand toCreateCommand(CreateCategoryRequest request);

    /**
     * Builds the {@link HexColor} — where an {@code InvalidHexColorException}
     * would surface (mapped to 422), though the DTO's {@code @Pattern} already
     * guards the structure, so in practice the value is well-formed here.
     */
    @Named("toHexColor")
    default HexColor toHexColor(String color) {
        return new HexColor(color);
    }

    @Named("toOptionalString")
    default Optional<String> toOptionalString(String value) {
        return Optional.ofNullable(value);
    }

    @Named("toOptionalCategoryId")
    default Optional<CategoryId> toOptionalCategoryId(UUID parentId) {
        return Optional.ofNullable(parentId).map(CategoryId::of);
    }

    // --- Outbound: read model -> response DTO (hand-written, see above) ---------

    default CategoryResponse toDto(CategoryView view) {
        return new CategoryResponse()
                .id(view.id().value())
                .type(toDtoType(view.type()))
                .name(view.name())
                .color(view.color().value())
                .icon(view.icon().orElse(null))
                .parentId(view.parent().map(CategoryId::value).orElse(null))
                .displayOrder(view.displayOrder())
                .archived(view.archived());
    }

    default CategoryNodeResponse toNodeDto(CategoryNode node) {
        return new CategoryNodeResponse()
                .id(node.id().value())
                .type(toDtoType(node.type()))
                .name(node.name())
                .color(node.color().value())
                .icon(node.icon().orElse(null))
                .displayOrder(node.displayOrder())
                .archived(node.archived())
                .children(node.children().stream().map(this::toNodeDto).toList());
    }

    // Enum name-based conversion: generated by MapStruct (compile-time checked
    // that every domain constant has a matching DTO constant).
    com.pecunia.category.web.dto.CategoryType toDtoType(com.pecunia.category.domain.CategoryType type);
}
